### ISSUE TITLE
Pimatic-LCD error Cannot write to device at i2c.writeByte

### ISSUE THREAD

**Issue by misakm** [pimatic/pimatic-lcd#2]
Hello,

I am facing an issue with pimatic-lcd or i2c plugin. I am using lcd to display current temperature and time based on rule every 5 seconds. After few hours lcd stops responding with following error:

debug [pimatic]: Error: Cannot write to device at i2c.writeByte (/i2c.coffee:58:10) at
i2c.tryCatcher (/root/pimatic-app/node_modules/pimatic-lcd/node_modules/i2c-
lcd/node_modules/bluebird/js/main/util.js:24:31) at i2c.ret [as writeByteAsync](eval at
<anonymous> %28/root/pimatic-app/node_modules/pimatic-lcd/node_modules/i2c-
lcd/node_modules/bluebird/js/main/promisify.js:154:12%29, <anonymous>:12:39) at /root/pimatic-
app/node_modules/pimatic-lcd/node_modules/i2c-lcd/lib/lcd.js:72:26 at tryCatcher
(/root/pimatic-app/node_modules/pimatic-lcd/node_modules/i2c-
lcd/node_modules/bluebird/js/main/util.js:24:31) at Promise._settlePromiseFromHandler
(/root/pimatic-app/node_modules/pimatic-lcd/node_modules/i2c-
lcd/node_modules/bluebird/js/main/promise.js:454:31) at Promise._settlePromiseAt
(/root/pimatic-app/node_modules/pimatic-lcd/node_modules/i2c-
lcd/node_modules/bluebird/js/main/promise.js:530:18) at Async._drainQueue (/root/pimatic-
app/node_modules/pimatic-lcd/node_modules/i2c-
lcd/node_modules/bluebird/js/main/async.js:84:12) at Async._drainQueues (/root/pimatic-
app/node_modules/pimatic-lcd/node_modules/i2c-
lcd/node_modules/bluebird/js/main/async.js:89:10) at Async.drainQueues (/root/pimatic-
app/node_modules/pimatic-lcd/node_modules/i2c-
lcd/node_modules/bluebird/js/main/async.js:14:14) at process._tickCallback (node.js:415:13

Firstly I thought that it is hardware isssue but python script is running ok
python2 /root/python-i2c-lcd/display.py test1~test2~test3~test4
Only pimatic restart helps but just for few hour...

Thank you for any idea how to fix it.
BR, Michal

**Comment by Tom-Jans** [comment]
I'm having the same error. Restarting pimatic doesn't work.

**Comment by mwittig** [comment]
Do you still have these errors? Works for me!

**Comment by mwittig** [comment]
No response. Assume this has been resolved. Please re-open otherwise
